# Generated by Django 5.0 on 2023-12-11 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("performance", "row", "seat")},
        ),
    ]
