# Generated by Django 5.0 on 2023-12-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_service", "0002_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="performance",
            options={"ordering": ["-showtime"]},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(
                blank=True, related_name="plays", to="theatre_service.actor"
            ),
        ),
        migrations.AlterField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="plays", to="theatre_service.genre"
            ),
        ),
    ]
